modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Mrbysco/Hex"
license="MIT"

[[mods]]
modId="hex"
version="${file.jarVersion}"
displayName="Hex"
displayURL="https://www.curseforge.com/minecraft/mc-mods/hex"
authors="Mrbysco, ShyNieke"
description='''
More enchantments? More fun? More fun for everyone!
'''
[[dependencies.hex]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"