modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/Hex/issues"
license="MIT"

[[mods]]
modId="hex"
version="${file.jarVersion}"
displayName="Hex"
displayURL="https://www.curseforge.com/minecraft/mc-mods/hex"
authors="Mrbysco, ShyNieke"
description='''
More enchantments? More fun? More fun for everyone!
'''
[[dependencies.hex]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.hex]]
modId="neoforge"
mandatory=true
versionRange="[20.2.86,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config = "hex.mixins.json"